package com.gestor.financeiro.model.enums;

public enum ImportFailureCode {
    EMPTY_FILE,
    DETECTION_FAILED,
    UNSUPPORTED_FORMAT,
    FORMAT_MISMATCH,
    CHARSET_UNSUPPORTED,
    STRUCTURE_LIMIT_EXCEEDED,
    HASH_MISMATCH,
    FILE_LIMIT_EXCEEDED,
    ROW_LIMIT_EXCEEDED,
    PARSE_FAILED,
    VALIDATION_FAILED,
    COMMIT_FAILED,
    REVERSAL_FAILED,
    UNKNOWN
}
